---
  - name: "kernel: vm.max_map_count=262144"
    sysctl:
      name: vm.max_map_count
      value: 262144
      state: present

  - name: "kernel: net.core.somaxconn=65535"
    sysctl:
      name: net.core.somaxconn
      value: 65535
      state: present

  - name: "kernel: net.ipv4.tcp_max_syn_backlog=65535"
    sysctl:
      name: net.ipv4.tcp_max_syn_backlog
      value: 65535
      state: present

  - name: "kernel: net.core.netdev_max_backlog=16384"
    sysctl:
      name: net.core.netdev_max_backlog
      value: 16384
      state: present

  - name: "kernel: net.ipv4.ip_local_port_range=1024 65535"
    sysctl:
      name: net.ipv4.ip_local_port_range
      value: "1024 65535"
      state: present
