---

###########################################################
# Add user Ansible                                        #
###########################################################

  - name: "add a new user ansible"
    user:
      name: "ansible"
      home: "/home/ansible"
      uid: 1001
      shell: "/bin/bash"
    when: users

  - name: "mkdir .ssh ansible"
    file:
      dest: "/home/ansible/.ssh/"
      owner: "ansible"
      group: "ansible"
      mode: 0700
      state: directory
    when: users

  - name: "add authorized keys ansible"
    file:
      dest: "/home/ansible/.ssh/authorized_keys"
      owner: "ansible"
      group: "ansible"
      mode: 0600
      state: touch
    when: users

  - name: "copy publickey ansible ansible"
    template:
      src: "ansible/public.j2"
      dest: "/home/ansible/.ssh/authorized_keys"
    when: users

  - name: "ansible users sudo privileges granted  ansible"
    lineinfile:
      dest: /etc/sudoers
      line: 'ansible ALL=(ALL) NOPASSWD: ALL'
    when: users


###########################################################
# Add user                                                #
###########################################################

  - name: "add a new group docker"
    group:
      name: docker
      gid: 999
      state: present

  - name: "add a new user"
    user:
      name: "{{ item.name }}"
      home: "/home/{{ item.name }}"
      uid: "{{ item.uid }}"
      shell: "{{ item.shell }}"
      groups: docker
    with_items:
      - "{{ users }}"
    when: users

  - name: "mkdir .ssh"
    file:
      dest: "/home/{{ item.name }}/.ssh/"
      owner: "{{ item.name }}"
      group: "{{ item.name }}"
      mode: 0700
      state: directory
    with_items:
      - "{{ users }}"
    when: users

  - name: "add authorized keys"
    file:
      dest: "/home/{{ item.name }}/.ssh/authorized_keys"
      owner: "{{ item.name }}"
      group: "{{ item.name }}"
      mode: 0600
      state: touch
    with_items:
      - "{{ users }}"
    when: users

  - name: "Set authorized key without validating the TLS/SSL certificates"
    authorized_key:
      user: "{{ item.name }}"
      state: present
      key: "https://github.com/{{ item.github }}.keys"
      validate_certs: False
    with_items:
      - "{{ users }}"
    when: users

  - name: "copy .ssh/rc"
    copy:
      src: .ssh/rc.sh
      dest: "/home/{{ item.name }}/.ssh/rc"
      owner: "{{ item.name }}"
      group: "{{ item.name }}"
      mode: 0755
    with_items:
      - "{{ users }}"
    when: users

  - name: "copy .zshrc"
    copy:
      src: dotfiles/.zshrc
      dest: "/home/{{ item.name }}/.zshrc"
      owner: "{{ item.name }}"
      group: "{{ item.name }}"
      mode: 0644
    with_items:
      - "{{ users }}"
    when: users

  - name: "{{ item.name }} users sudo privileges granted"
    lineinfile:
      dest: /etc/sudoers
      line: '{{ item.name }} ALL=(ALL) NOPASSWD: ALL'
    with_items:
      - "{{ users }}"
    when: users
