---
  - name: "Set hostname"
    hostname:
      name: "{{ ansible_hostname }}.{{ group_domain }}"

  - name: "Set /etc/hosts"
    lineinfile:
      dest: /etc/hosts
      regexp: "^127.0.1.1.*"
      insertafter: "^127.0.1.1.*"
      line: "127.0.1.1	{{ ansible_hostname }} {{ ansible_hostname }}.{{ group_domain }}"
