---
  - name: "Uninstall old versions"
    apt:
      name: "{{ item }}"
      state: absent
    ignore_errors: true
    changed_when: false
    with_items:
      - docker
      - docker-engine

  - name: "1. Install packages to allow apt to use a repository over HTTPS:"
    apt:
      name: "{{ item }}"
      update_cache: yes
    ignore_errors: true
    changed_when: false
    with_items:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common

  - name: "2.1 Add Docker’s official GPG key:"
    apt_key:
      id: 0EBFCD88
      url: "https://download.docker.com/linux/ubuntu/gpg"
      state: present
    changed_when: false

  - name: "3. Use the following command to set up the stable repository."
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ lsb_release }} stable
      state: present
    changed_when: false

  - name: "2. Install the latest version of Docker"
    apt:
      name: docker-ce={{ docker_version }}-{{ lsb_release }}
      state: present
      update_cache: yes
    changed_when: false
